### ISSUE TITLE
create username and password db accounts for data analysts

### ISSUE THREAD

**Issue by alepietrobon** [onaio/sre-tooling#31]
Hope i'm posting this in the right project. If not, please someone let me know. Thx. 

**Background**
Data analysis requires interacting with databases and structuring data. Today, the main tool to do so for data analysts is the SQL lab functionality within Superset. This tool is fine for ad-hoc tasks but not very secure nor scalable for robust data-analysis workflows. In particular:
- SQL lab does not allow github integration, making it super likely that queries are not stored or saved for reuse (e.g. views or tables saved in the db that have no clear origin)
- SQL lab does not allow for personalized permissions: nowadays even clients with sql lab access can drop tables within our databases (production!). 
- from my understanding, queries run by any individual user are impossible to trace back
- SQL lab is not futureproof because not all projects and databases at Ona will require superset deployments
- SQL lab does not allow to package scripts into sqitch migrations, making it harder for data analysts to comply with data-engineering best practices 

**Request / proposal**
After discussing with @pld , we agreed it can make sense to have unique database credentials for data analysts to the same databases that superset has access to. The access permissions can be managed by a Database Administrator (can be myself to start, plus whoever else we decide).

For access control, we can elaborate a policy but broadly follow the following principles:
- data analysts can read prod data, otherwise it's hard to perform data analysis. 
- db performance can be maintained by setting a max query duration 
- data analysts can write in dedicated test schemas, to be maintained by the Database Administrator
- Supeset dashboards or any other reporting should point to non-test tables once any project enters support/maintenance mode
- tables/views generated in the non-test schemas require code review (via db migration)

**Priority**
This is not an immediate client request, just a good opportunity to improve internal tooling and collaboration while reducing the data risks that are inherent to our existing way of working. It can be prioritized accordingly. 

cc. @ukanga @jasonrogena @moshthepitt

**Comment by pld** [comment]
This overlaps w/both SRE and Canopy/data eng team responsibilities, since this is security related having it here first makes sense, we can discuss if we need to create sub issues in other repos or otherwise delegate this.

Let's discuss on the weekly SRE meeting, please read through before the meeting

**Comment by pld** [comment]
https://github.com/onaio/playbooks/issues/2760
